- frontend/src/pages/Coding-zone/CodingZoneMain.js
- frontend/src/pages/css/codingzone/codingzone-main.css
출석 진행률 표시를 텍스트 형식에서 프로그래스 바 형태로 수정
- #154
> [FE-#154] 출석 횟수를 텍스에서 프로그래스 바 형태로 수정

- frontend/src/pages/css/codingzone/codingzone-main.css
코딩존(1,2) 구분 버튼 크기 조정
- #153 
**수정 전**
**수정  후**
> [FE-#153] 코딩존(1,2) 구분 버튼 크기 조정

- backend/src/main/java/com/icehufs/icebreaker/domain/article/dto/object/ArticleListItem.java
- backend/src/main/java/com/icehufs/icebreaker/domain/article/dto/object/CommentListItem.java
- backend/src/main/java/com/icehufs/icebreaker/domain/article/dto/response/GetArticleListResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/article/dto/response/GetCommentListResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/article/dto/response/GetUserArticleListResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/auth/dto/object/JwtToken.java
- backend/src/main/java/com/icehufs/icebreaker/domain/auth/dto/response/RegenerateTokenResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/auth/dto/response/SignInResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/auth/service/implement/AuthServiceImplement.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/object/CodingZoneAssitantListItem.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/object/CodingZoneClassListItem.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/object/CodingZoneStudentListItem.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/object/GroupInfListItem.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/object/PersAttendManagListItem.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/object/ReservedClassListItem.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/GetCodingZoneAssitantListResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/GetCodingZoneStudentListResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/GetListOfCodingZoneClassForNotLogInResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/GetListOfCodingZoneClassResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/GetListOfGroupInfResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/GetPersAttendListItemResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/GetReservedClassListItemResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
- backend/src/main/java/com/icehufs/icebreaker/provider/JwtProvider.java
- DTO 형태의 파일을 VO로 잘못 패키징 한 것을 수정.
#170 
> [BE-#170] article, auth, codingzone 도메인의 DTOodject 파일들의 패키지 수정

- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
- 이전기능: 코딩존 메인 페이지에 반환되는 예약가능한 다음주 수업들이 금주 _목요일에서 일요일 사이_에만 API를 통해 반환 가능
- 수정된 기능: 코딩존 메인 페이지에 반환되는 예약가능한 다음주 수업들이 금주 _목요일 오후4시에서 일요일 사이_에만 API를 통해 반환 가능
- #155 
> [BE-#155] CodingZone 메인페이지에서 반환되는 예약 가능한 수업들의 반환 가능 기간 수정

- frontend/src/pages/HomePage/HomePage.js
- frontend/src/shared/api/AuthApi.js
> [FE-#175] RT 응답 추가

- frontend/src/pages/ArticlePage/Components/ShowPage.js
어떤 변경사항이 있는지 설명해주세요.
- 관련된 이슈 번호를 적어주세요 (#issue_number)
> [FE] 테스트를 위한 Pull request

- frontend/src/entities/api/ArticleApi.js
- frontend/src/features/ArticlePage/BlogForm.js
- frontend/src/features/ArticlePage/hooks/UseBlogForm.js
- frontend/src/pages/ArticlePage/Components/ShowPage.js
1.어제 테스트하면서 변경했던 내용을 원래대로 복구함.
2.코드 리팩토링 전에 BlogForm 파일에서 UI와 로직이 한 파일에 섞여 있어 이를 분리함.
- #178
> refactor: blogForm ui,로직 코드 분리

- frontend/src/pages/Coding-zone/InquiryModal.js
문의하기 모달창 경로 이상으로 오류 발생하여 경로 수정
> feat: 경로 오류 수정

- frontend/src/app/App.js
- frontend/src/app/App.test.js
- frontend/src/app/index.css
- frontend/src/app/reportWebVitals.js
- frontend/src/index.js
App layer 폴더 구조 형성
app.js 코드 수정 -> 라우터 추가
index.js 코드 수정
#168 
> [FE-#168 ]FSD-app layer 형성

- frontend/src/features/auth/components/modals/LoginForm.js
- frontend/src/features/auth/components/modals/Mypage.js
- frontend/src/pages/ArticlePage/Components/ShowPage.js
- frontend/src/widgets/layout/Header/Navbar.js
1. 파일명과 import 문에서 대소문자가 일치하도록 수정
2. 특정게시글을 새로고침 시 로딩되는동안 "게시글이 존재하지 않습니다"문장이 0.1초정도 보였는데
그 코드에 그냥 문장대신 배너만 보이도록 수정함
> fix: 특정게시글들어갈때"게시글존재하지습니다"문구보이는거 수정

- frontend/src/entities/api/CodingZone/AdminApi.js
- frontend/src/entities/api/CodingZone/StudentApi.js
- frontend/src/features/api/Admin/Codingzone/AttendanceApi.js
- frontend/src/features/api/Admin/Codingzone/AuthApi.js
- frontend/src/features/api/Admin/Codingzone/ClassApi.js
- frontend/src/features/api/Admin/UserApi.js
- frontend/src/features/api/CodingzoneApi.js
- frontend/src/pages/AuthHandle.js
- frontend/src/pages/Coding-zone/CodingZoneAttendanceAssistant.js
- frontend/src/pages/Coding-zone/CodingZoneAttendanceManager.js
- frontend/src/pages/Coding-zone/CodingZoneMain.js
- frontend/src/pages/Coding-zone/CodingZoneMyAttendance.js
- frontend/src/pages/Coding-zone/CodingZoneRegist.js
- frontend/src/shared/api/AuthApi.js
코딩존 메인 페이지, 코딩존 등록 페이지, 코딩존 출석 페이지 -> RT 응답 연동
ATE 응답 처리 추가 후 토큰 재발급 API 연동
#175 
> [FE-#175 ]코딩존 페이지에 RT 재발급 API 추가

- .github/workflows/server-deploy.yml
- backend/Dockerfile
- 수동 배포로 작동하던 서버를 자동 배포로 구현해주었습니다.
- #201 
> [Feature] 서버 자동 배포 구현

- frontend/src/pages/Coding-zone/CodingZoneMain.js
코딩존 메인페이지 예약 버튼을 누르고 취소를 했을때 바로 화면 렌더링이 되지 않는 문제
> [FE]코딩존메인페이지 예약버튼 버그 수정

- frontend/src/entities/api/ArticleApi.js
- frontend/src/entities/api/CodingZone/AdminApi.js
- frontend/src/entities/api/CodingZone/StudentApi.js
- frontend/src/entities/api/UserApi.js
- frontend/src/features/api/Admin/Codingzone/AttendanceApi.js
- frontend/src/features/api/Admin/Codingzone/AuthApi.js
- frontend/src/features/api/Admin/Codingzone/ClassApi.js
- frontend/src/features/api/Admin/Codingzone/InquiryApi.js
- frontend/src/features/api/Admin/CommentsApi.js
- frontend/src/features/api/Admin/UserApi.js
- frontend/src/features/api/ArticleApi.js
- frontend/src/features/api/CodingzoneApi.js
- frontend/src/pages/ArticlePage/Components/ShowPage.js
- frontend/src/shared/api/AuthApi.js
- frontend/src/shared/api/EmailApi.js
어떤 변경사항이 있는지 설명해주세요.
- 관련된 이슈 번호를 적어주세요 (#issue_number)
> [FE-#175] fix: 특정게시물 alert오류 해결

- frontend/src/entities/api/ArticleApi.js
- frontend/src/features/api/Admin/UserApi.js
- frontend/src/features/api/ArticleApi.js
- frontend/src/shared/api/AuthApi.js
> [FE] Feature/FE-157/익명게시판 버그 수정

- frontend/src/entities/api/ArticleApi.js
- frontend/src/entities/api/CodingZone/AdminApi.js
- frontend/src/entities/api/CodingZone/StudentApi.js
- frontend/src/entities/api/UserApi.js
- frontend/src/features/api/Admin/Codingzone/AttendanceApi.js
- frontend/src/features/api/Admin/Codingzone/AuthApi.js
- frontend/src/features/api/Admin/Codingzone/ClassApi.js
- frontend/src/features/api/Admin/Codingzone/InquiryApi.js
- frontend/src/features/api/Admin/CommentsApi.js
- frontend/src/features/api/Admin/UserApi.js
- frontend/src/features/api/ArticleApi.js
- frontend/src/features/api/CodingzoneApi.js
- frontend/src/shared/api/AuthApi.js
- frontend/src/shared/api/EmailApi.js
API 도메인을 로칼 변수 .env로 수정
- #205
> [FE-#205] API 도메인 로칼 변수(.env) 설정

- frontend/src/pages/ArticlePage/Components/ShowPage.js
> hofix:익명게시판화면로딩문제해결

- backend/src/main/java/com/icehufs/icebreaker/config/RedisConfig.java
- Redis 보안요소 점검 간에 비밀번호 추가
- 없음
> [Fix] Redis 비밀번호 설정

- frontend/src/app/App.js
- frontend/src/features/api/Admin/Codingzone/ClassApi.js
- frontend/src/features/auth/components/Modal/LoginForm.js
- frontend/src/pages/Coding-zone/CodingZoneRegist.js
- frontend/src/pages/Coding-zone/CodingZoneSetting.js
- frontend/src/pages/css/codingzone/Codingzone_setting.css
> [FE-#245] 코딩존 매핑 페이지 추가

- frontend/src/pages/Coding-zone/CodingZoneRegist.js
- 머지 후에 오류 난 것을 확인해서 수정후에 다시 푸시합니다.
- 중점적으로 확인이 필요한 부분이 있다면 작성해 주세요.
> fix: 머지 후 오류 수정

- frontend/src/entities/api/CodingZone/AdminApi.js
- frontend/src/pages/Coding-zone/CodingZoneRegist.js
- 조 등록 기능과 수업 등록 기능 병합
- 표 헤더 <요일 날짜 시간 조교 과목명 코딩존 인원>에서
<요일 날짜 시간 과목명 조교 인원>으로 변경
- 디자인 수정 전입니다.
- 과목 선택 시 과목에 해당하는 조교 리스트 출력
- 날짜 오늘에 해당하는 날짜를 기본값으로 변경
- API 경로는 다영이 PR 머지 후에 codingzones로 변경할 예정입니다.
- 수업 등록이 정상적으로 작동하는지 확인 부탁드립니다.
포스트맨에서 실행되는 모습
> [FE-#276] 기존의 조 등록과 수업 등록 기능 병합

- frontend/src/pages/Coding-zone/CodingZoneRegist.js
- currentNumber가 빠져있는것을 확인
요청본문이 이렇지만 코드상 currentNumber 빠져있는것 확인 후 추가함
- 중점적으로 확인이 필요한 부분이 있다면 작성해 주세요.
> [FE-#289] 수업 등록 API 수정

- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/AttendanceService.java
import문을 수정했습니다.
import jakarta.transaction.Transactional;를 삭제하고
import org.springframework.transaction.annotation.Transactional; 를 추가하였습니다.
- 중점적으로 확인이 필요한 부분이 있다면 작성해 주세요.
- 추가로 참고해야 할 내용이나 스크린샷이 있다면 작성해 주세요.
close #355
> fix : import 문 수정

- frontend/src/pages/AuthHandle.js
- frontend/src/pages/Coding-zone/CodingZoneRegist.js
- frontend/src/pages/Coding-zone/CodingZoneSetting.js
- API가 수정되면서 수정해야할 페이지들을 수정
- 원래 작동했던 수업 등록 페이지와 코딩존 설정 페이지가 변경된 API를 적용하지 않아 작동하지 않았습니다. 따라서 두 페이지가 다시 정상적으로 작동하도록 수정했습니다.
> [FE-#329] API 수정하면서 수정 못한 페이지 수정

- frontend/src/features/api/Admin/Codingzone/InquiryApi.js
- 코딩존 조교 정보 반환 API 경로 수정
- API 경로 도메인 이름 수정
- 없음.
- 없음.
> [FE-346] 코딩존 조교 정보 반환 API 경로 수정

- frontend/src/features/api/Admin/Codingzone/ClassApi.js
- frontend/src/pages/Coding-zone/CodingZoneAttendanceAssistant.js
- frontend/src/pages/Coding-zone/CodingZoneAttendanceEA.js
- frontend/src/shared/ui/navigation/CodingZoneNavigation.js
- 학기초기화 API 수정
- 학생조교 권한 출결관리 API 수정
- 네비게이션 바 라우팅 문제 해결
1️⃣ 학기초기화 API 수정
URL 경로와 요청본문에 data 추가
-> 데이터베이스에서 잘 작동하는거 확인했습니다.
2️⃣ 학생조교 권한 출결관리 API 수정
URL 경로와 요청본문에 data 추가
-> 데이터베이스에서 잘 작동하는거 확인했습니다.
3️⃣ 네비게이션 바 라우팅 문제 해결
하단의 출결관리를 누르면 상단의 출결관리가 active 되어야하는데 코딩존 예약이 active되는 문제가 있어서 해결했습니다.
> [FE-#355] API 수정

- frontend/src/pages/css/codingzone/CodingClassRegist.css
- 수업 등록 페이지에서 표와 조 버튼 색상이 달라서 표 색과 똑같이(#052940) 수정했습니다.
> [FE-#359] 조 버튼 색상 수정

- backend/src/main/java/com/icehufs/icebreaker/domain/auth/controller/AdminSubjectController.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/dto/response/CodingZoneClassInfoResponseDto.java
- backend/src/main/java/com/icehufs/icebreaker/domain/codingzone/service/implement/CodingZoneServiceImplement.java
응답이 currentNumber와 maximumNumber를 포함하도록 수정
dto를 수정하였습니다.
AdminSubjectController에서 result 변수명을 codingZoneClasses로 변경하였습니다.
- 중점적으로 확인이 필요한 부분이 있다면 작성해 주세요.
- 추가로 참고해야 할 내용이나 스크린샷이 있다면 작성해 주세요.
close #363
> fix : 과사 조교 - 특정 과목 , 날짜에 해당하는 코딩존 목록 반환 api 수정

- frontend/src/app/App.js
- frontend/src/pages/Coding-zone/CodingZoneAttendanceManager.js
- frontend/src/pages/Coding-zone/CodingZoneMain.js
- frontend/src/pages/Coding-zone/CodingZoneMyAttendance.js
- frontend/src/shared/ui/boardbar/CodingZoneBoardbar.js
- frontend/src/shared/ui/navigation/CodingZoneNavigation.js
- 모든 URL 경로 소문자와 중간바로 통일
- 핵심 로직 설명 및 리뷰 시 참고 사항
> [FE-#381] 경로 수정

- frontend/src/pages/Coding-zone/CodingZoneRegist.js
- frontend/src/pages/Coding-zone/CodingZoneSetting.js
- 주요 기능/버그 수정 요약
1️⃣ 코딩존 등록 페이지
- 원래는 추가 버튼을 누르면 행이 생성되었지만 디폴트로 하나의 행이 생기게 변경
-> 수업 등록 들어가자마자 디폴트 행이 보이는 모습
2️⃣ 코딩존 설정 페이지
- 코딩존 등록 페이지와 동일하게 디폰트로 하나의 행 생기게 변경
- 원래는 등록 순으로 정렬이 되었는데, 번호 순으로 정렬되게 수정
> [FE-#389] 수업 등록, 코딩존 설정 페이지 디폴트 행 추가

- frontend/src/pages/Coding-zone/CodingZoneMain.js
- frontend/src/pages/css/codingzone/codingzone-main.css
- frontend/src/shared/ui/navigation/CodingZoneNavigation.css
- 네비게이션바 잘림 문제
- 과목 버튼 잘림 문제
- 등록된 코딩존이 없을 때 뜨는 부엉이 사진 잘림 문제
- 반응형을 1280, 1024, 768, 480px 기준으로 구현했습니다.
- 네비게이션바와 과목 버튼은 반응형에 맞게 transform: scale을 사용해 크기를 조절하였습니다.
> [FE-#404] 코딩존 예약 페이지 반응형 구현

- frontend/src/pages/css/codingzone/codingzone_attend.css
> release: 2.3.7
